#!/bin/bash

# I got this from a co-worker many moons ago. Unfortunately, I don't remember
# who. Basically, if a tree program is not installed, fake it with this.

if ! command -v tree > /dev/null 2>&1; then

  alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"

fi
